<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { useRoute, useRouter } from 'vue-router'
import { VaButton, VaInnerLoading } from 'vuestic-ui'
import { usePondsStore } from '../../stores/ponds.store'
import { usePondBatchesStore } from '../../stores/pond-batches.store'
import { SPECIES_LABELS, STATUS_LABELS, type BatchInput, type BatchItem, type BatchStatusCode, type Species } from '../../types'

const route = useRoute(); const router = useRouter(); const store = usePondBatchesStore(); const pondsStore = usePondsStore()
const { items, loading, saving, error } = storeToRefs(store)
const farmId = computed(() => String(route.params.farmId)); const pondId = computed(() => String(route.params.pondId)); const pondName = ref('')
const showForm = ref(false); const editingId = ref<string | null>(null); const formError = ref(''); const success = ref('')
const form = reactive({ batchCode: '', species: 'SHRIMP' as Species, seedSource: '', seedQuantity: '' as string | number, stockingDate: '', expectedHarvestDate: '', actualHarvestDate: '', yieldQuantity: '' as string | number, status: 'GROWING' as BatchStatusCode, note: '' })
const statuses = Object.entries(STATUS_LABELS) as [BatchStatusCode, string][]; const species = Object.entries(SPECIES_LABELS) as [Species, string][]
const canEnterHarvest = computed(() => Boolean(editingId.value) && ['HARVESTED', 'COMPLETED'].includes(form.status))
const numeric = (value: string | number) => value === '' ? null : Number(value)
const dateOnly = (value: string | null | undefined) => value ? value.slice(0, 10) : ''
function reset() { editingId.value = null; Object.assign(form, { batchCode: '', species: 'SHRIMP', seedSource: '', seedQuantity: '', stockingDate: '', expectedHarvestDate: '', actualHarvestDate: '', yieldQuantity: '', status: 'GROWING', note: '' }); formError.value = '' }
function openCreate() { reset(); showForm.value = true }
function openEdit(item: BatchItem) { editingId.value = item.id; Object.assign(form, { batchCode: item.batch_code, species: item.species, seedSource: item.seed_source ?? '', seedQuantity: item.seed_quantity, stockingDate: dateOnly(item.stocking_date), expectedHarvestDate: dateOnly(item.expected_harvest_date), actualHarvestDate: dateOnly(item.actual_harvest_date), yieldQuantity: item.yield_quantity ?? '', status: item.status, note: item.note ?? '' }); showForm.value = true }
function close() { showForm.value = false; reset() }
async function submit() {
  formError.value = ''; success.value = ''
  if (!form.batchCode.trim() || !form.stockingDate || numeric(form.seedQuantity) === null) { formError.value = 'Vui lòng nhập mã vụ, số lượng giống và ngày thả giống'; return }
  const payload: BatchInput = { batchCode: form.batchCode.trim(), species: form.species, seedSource: form.seedSource.trim() || null, seedQuantity: Number(form.seedQuantity), stockingDate: form.stockingDate, expectedHarvestDate: form.expectedHarvestDate || null, status: form.status, note: form.note.trim() || null }
  if (editingId.value) {
    payload.actualHarvestDate = canEnterHarvest.value ? (form.actualHarvestDate || null) : null
    payload.yieldQuantity = canEnterHarvest.value ? numeric(form.yieldQuantity) : null
  }
  try { if (editingId.value) { await store.update(farmId.value, pondId.value, editingId.value, payload); success.value = 'Đã cập nhật vụ nuôi' } else { await store.create(farmId.value, pondId.value, payload); success.value = 'Đã tạo vụ nuôi' }; close() } catch { formError.value = error.value }
}
async function remove(item: BatchItem) { if (!confirm(`Xóa vụ “${item.batch_code}”?`)) return; try { await store.remove(farmId.value, pondId.value, item.id); success.value = 'Đã xóa vụ nuôi' } catch {} }
onMounted(async () => { await pondsStore.load(farmId.value); pondName.value = pondsStore.items.find((x) => x.id === pondId.value)?.pond_name ?? ''; await store.load(farmId.value, pondId.value) })
</script>

<template><main class="page"><button class="back" @click="router.push({ name: 'ponds', params: { farmId } })">← Danh sách ao</button><header><div><p class="eyebrow">{{ pondName }}</p><h1>Các vụ nuôi</h1></div><va-button gradient @click="openCreate">+ Tạo vụ nuôi</va-button></header><p v-if="success" class="notice success">{{ success }}</p><p v-if="error" class="notice error">{{ error }}</p><va-inner-loading :loading="loading"><div v-if="!loading && !items.length" class="empty"><h2>Chưa có vụ nuôi</h2><p>Tạo vụ nuôi đầu tiên cho ao này.</p><va-button @click="openCreate">Tạo vụ nuôi</va-button></div><div v-else class="grid"><article v-for="item in items" :key="item.id"><div class="top"><strong>{{ item.batch_code }}</strong><span>{{ STATUS_LABELS[item.status] }}</span></div><h2>{{ SPECIES_LABELS[item.species] }}</h2><dl><div><dt>Ngày thả</dt><dd>{{ dateOnly(item.stocking_date) }}</dd></div><div><dt>Số lượng giống</dt><dd>{{ item.seed_quantity.toLocaleString('vi-VN') }}</dd></div><div><dt>Dự kiến thu hoạch</dt><dd>{{ dateOnly(item.expected_harvest_date) || '—' }}</dd></div></dl><footer><va-button preset="secondary" size="small" @click="router.push({ name: 'farming-logs', params: { farmId, pondId, batchId: item.id } })">Nhật ký nuôi</va-button><va-button preset="secondary" size="small" @click="openEdit(item)">Chỉnh sửa</va-button><va-button preset="plain" color="danger" size="small" @click="remove(item)">Xóa</va-button></footer></article></div></va-inner-loading>
<div v-if="showForm" class="backdrop" @click.self="close"><section class="modal"><header><h2>{{ editingId ? 'Cập nhật vụ nuôi' : 'Tạo vụ nuôi' }}</h2><button @click="close">×</button></header><form @submit.prevent="submit"><label>Mã vụ nuôi *<input v-model="form.batchCode" maxlength="100" placeholder="VU-2026-01" /></label><label>Loài nuôi *<select v-model="form.species"><option v-for="([value,label]) in species" :key="value" :value="value">{{ label }}</option></select></label><label>Nguồn giống<input v-model="form.seedSource" maxlength="255" /></label><label>Số lượng con giống *<input v-model="form.seedQuantity" type="number" min="1" step="1" /></label><label>Ngày thả giống *<input v-model="form.stockingDate" type="date" /></label><label>Ngày dự kiến thu hoạch<input v-model="form.expectedHarvestDate" type="date" /></label><label v-if="editingId">Trạng thái<select v-model="form.status"><option v-for="([value,label]) in statuses" :key="value" :value="value">{{ label }}</option></select></label><template v-if="canEnterHarvest"><label>Ngày thu hoạch thực tế<input v-model="form.actualHarvestDate" type="date" /></label><label>Sản lượng thu hoạch (kg)<input v-model="form.yieldQuantity" type="number" min="0" step="0.01" /></label></template><label>Ghi chú<textarea v-model="form.note" rows="3"></textarea></label><p v-if="formError" class="form-error">{{ formError }}</p><footer><va-button preset="secondary" type="button" @click="close">Hủy</va-button><va-button type="submit" :loading="saving">Lưu</va-button></footer></form></section></div></main></template>

<style scoped>
.page{width:min(1180px,calc(100% - 2.5rem));margin:auto;padding:2rem 0 4rem}.back{border:0;background:none;color:#0f766e;font-weight:700;cursor:pointer;margin-bottom:1rem}.page>header,.modal header,.top,article footer,form footer{display:flex;justify-content:space-between;align-items:center;gap:1rem}.eyebrow{color:#0f766e;font-weight:800;margin:0 0 .3rem}h1{margin:0}.notice{padding:.8rem 1rem;border-radius:10px}.success{background:#ecfdf5;color:#047857}.error,.form-error{background:#fef2f2;color:#b91c1c}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:1.5rem}article,.empty{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:1.25rem}.top span{font-size:.75rem;background:#ecfdf5;color:#047857;padding:.3rem .55rem;border-radius:99px}dl div{display:flex;justify-content:space-between;border-top:1px solid #f1f5f9;padding:.6rem 0}dd{margin:0;font-weight:600}.empty{text-align:center;margin-top:1.5rem;padding:4rem}.backdrop{position:fixed;inset:0;z-index:100;background:#0f172a88;display:grid;place-items:center;padding:1rem}.modal{background:#fff;border-radius:18px;padding:1.5rem;width:min(700px,100%);max-height:90vh;overflow:auto}.modal header button{border:0;border-radius:50%;font-size:1.4rem;width:34px;height:34px}.modal form{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.modal label{display:grid;gap:.4rem;font-weight:700;font-size:.86rem}.modal input,.modal select,.modal textarea{padding:.75rem;border:1px solid #cbd5e1;border-radius:10px;font:inherit}.form-error,.modal form footer{grid-column:1/-1;margin:0;padding:.7rem;border-radius:8px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.grid,.modal form{grid-template-columns:1fr}.page>header{align-items:stretch;flex-direction:column}}
</style>
